# Production Supabase Configuration
# This file should be used to configure production environment

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"

[inbucket]
enabled = false

[storage]
enabled = true
file_size_limit = "50MiB"
buckets = [
  { name = "excel-files", public = false },
  { name = "reports", public = false }
]

[auth]
enabled = true
site_url = "https://your-production-domain.com"
additional_redirect_urls = ["https://your-production-domain.com/**"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
secure_password_change_enabled = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true
template_path = "./supabase/templates"

[auth.sms]
enable_signup = false

[edge_functions]
enabled = true
inspector_port = 8083

[analytics]
enabled = true
port = 54327
vector_port = 54328
backend = "postgres"