project_id = "hlwchpmogvwmpuvwmvwv"

[functions.process-excel]
verify_jwt = false

[functions.admin-users]
verify_jwt = true

[functions.claude-testing-processor]
verify_jwt = false

[functions.claude-testing-analyzer]
verify_jwt = false