name: Continuous Integration

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  NODE_VERSION: '18'

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    outputs:
      test-status: ${{ steps.test-summary.outputs.status }}
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Environment Debug
        run: |
          set -e
          echo "🔍 Environment Variables Debug (masked sensitive values):"
          echo "NODE_VERSION: ${{ env.NODE_VERSION || 'not-set' }}"
          echo "CI: ${CI:-not-set}"
          echo "GITHUB_REF: ${GITHUB_REF:-not-set}"
          echo "GITHUB_SHA: ${GITHUB_SHA:-not-set}"
          echo "VITE_SUPABASE_URL: $(echo '${{ secrets.VITE_SUPABASE_URL || 'https://demo.supabase.co' }}' | head -c 20)***"
          echo "VITE_SUPABASE_ANON_KEY: $(echo '${{ secrets.VITE_SUPABASE_ANON_KEY || 'demo-key' }}' | head -c 10)***"
          echo "✅ Environment debug completed"
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION || '18' }}
          cache: 'npm'
          
      - name: Install dependencies
        run: |
          set -e
          echo "📦 Installing dependencies..."
          npm ci || {
            echo "❌ npm ci failed"
            echo "🔍 Debugging npm installation:"
            npm --version
            node --version
            ls -la package*.json
            exit 1
          }
          echo "✅ Dependencies installed successfully"
        
      - name: Install Playwright browsers
        run: |
          set -e
          echo "🎭 Installing Playwright browsers..."
          node scripts/install-browsers.cjs || {
            echo "⚠️ Playwright browser installation failed (non-critical)"
            echo "Continuing with tests that don't require browsers"
          }
        continue-on-error: true  # Allow browser installation to fail in CI
        
      - name: Run linter
        run: |
          set -e
          echo "🔍 Running linter..."
          npm run lint || {
            echo "⚠️ Linting issues found (non-critical for CI)"
            echo "Please review and fix linting issues"
          }
        continue-on-error: true  # Allow linting issues for now
        
      - name: Run unit tests
        id: unit-tests
        run: |
          set -e
          echo "🧪 Running unit tests..."
          npm run test || {
            echo "❌ Unit tests failed"
            exit 1
          }
          echo "✅ Unit tests completed successfully"
        env:
          CI: true
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL || 'https://demo.supabase.co' }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY || 'demo-key' }}
          
      - name: Run E2E tests
        id: e2e-tests
        run: |
          set -e
          echo "🎭 Running E2E tests..."
          npm run test:e2e:safe || {
            echo "⚠️ E2E tests failed (allowing failures in CI)"
            echo "E2E test failures are logged but won't fail the build"
          }
        env:
          CI: true
          ALLOW_E2E_FAILURES: 'true'
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL || 'https://demo.supabase.co' }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY || 'demo-key' }}
          
      - name: Run build
        id: build
        run: |
          set -e
          echo "🏗️ Building application..."
          npm run build || {
            echo "❌ Build failed"
            echo "🔍 Build debugging info:"
            echo "Node version: $(node --version)"
            echo "NPM version: $(npm --version)"
            ls -la dist/ 2>/dev/null || echo "No dist directory found"
            exit 1
          }
          echo "✅ Build completed successfully"
        env:
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL || 'https://demo.supabase.co' }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY || 'demo-key' }}
          
      - name: Test Summary
        id: test-summary
        if: always()
        run: |
          set -e
          echo "📊 Test Summary Report:"
          echo "===================="
          
          # Check step outcomes
          UNIT_TESTS="${{ steps.unit-tests.outcome || 'skipped' }}"
          E2E_TESTS="${{ steps.e2e-tests.outcome || 'skipped' }}"
          BUILD="${{ steps.build.outcome || 'skipped' }}"
          
          echo "Unit Tests: $UNIT_TESTS"
          echo "E2E Tests: $E2E_TESTS" 
          echo "Build: $BUILD"
          
          # Determine overall status
          if [[ "$UNIT_TESTS" == "success" && "$BUILD" == "success" ]]; then
            echo "status=success" >> $GITHUB_OUTPUT
            echo "✅ Overall Status: SUCCESS - Critical tests passed"
          else
            echo "status=failure" >> $GITHUB_OUTPUT
            echo "❌ Overall Status: FAILURE - Critical tests failed"
          fi
        
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: |
            coverage/
            test-results/
            playwright-report/
          retention-days: 7

  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    
    outputs:
      security-status: ${{ steps.security-summary.outputs.status }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Environment Debug
        run: |
          set -e
          echo "🔍 Security Environment Debug:"
          echo "NODE_VERSION: ${{ env.NODE_VERSION || 'not-set' }}"
          echo "GITHUB_REF: ${GITHUB_REF:-not-set}"
          echo "✅ Security environment debug completed"
        
      - name: Run npm audit
        id: npm-audit
        run: |
          set -e
          echo "🔐 Running npm security audit..."
          npm audit --audit-level=high || {
            echo "⚠️ Security audit completed with warnings"
            echo "Review security vulnerabilities in the audit output above"
          }
        continue-on-error: true
        
      - name: Run CodeQL Analysis
        uses: github/codeql-action/init@v3
        with:
          languages: typescript
          
      - name: Perform CodeQL Analysis
        id: codeql-analysis
        uses: github/codeql-action/analyze@v3
        
      - name: Security Summary
        id: security-summary
        if: always()
        run: |
          set -e
          echo "🔐 Security Summary Report:"
          echo "========================="
          
          NPM_AUDIT="${{ steps.npm-audit.outcome || 'skipped' }}"
          CODEQL="${{ steps.codeql-analysis.outcome || 'skipped' }}"
          
          echo "NPM Audit: $NPM_AUDIT"
          echo "CodeQL Analysis: $CODEQL"
          
          if [[ "$CODEQL" == "success" ]]; then
            echo "status=success" >> $GITHUB_OUTPUT
            echo "✅ Security Status: PASSED"
          else
            echo "status=failure" >> $GITHUB_OUTPUT
            echo "❌ Security Status: ISSUES FOUND"
          fi

  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: [test, security-scan]
    if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Environment Debug
        run: |
          set -e
          echo "🔍 Staging Deployment Environment Debug:"
          echo "NODE_VERSION: ${{ env.NODE_VERSION || 'not-set' }}"
          echo "STAGING_SUPABASE_URL: $(echo '${{ secrets.STAGING_SUPABASE_URL || secrets.VITE_SUPABASE_URL || 'https://demo.supabase.co' }}' | head -c 20)***"
          echo "✅ Staging environment debug completed"
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION || '18' }}
          cache: 'npm'
          
      - name: Install dependencies
        run: |
          set -e
          echo "📦 Installing dependencies for staging..."
          npm ci || {
            echo "❌ Staging dependency installation failed"
            exit 1
          }
          echo "✅ Staging dependencies installed"
        
      - name: Build for staging
        run: |
          set -e
          echo "🏗️ Building for staging environment..."
          npm run build:dev || {
            echo "❌ Staging build failed"
            exit 1
          }
          echo "✅ Staging build completed"
        env:
          VITE_SUPABASE_URL: ${{ secrets.STAGING_SUPABASE_URL || secrets.VITE_SUPABASE_URL || 'https://demo.supabase.co' }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.STAGING_SUPABASE_ANON_KEY || secrets.VITE_SUPABASE_ANON_KEY || 'demo-key' }}
          
      - name: Deploy to staging
        run: |
          set -e
          echo "🚀 Deploying to staging environment..."
          # Add actual deployment steps here
          echo "✅ Staging deployment completed"

  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: [test, security-scan]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Environment Debug
        run: |
          set -e
          echo "🔍 Production Deployment Environment Debug:"
          echo "NODE_VERSION: ${{ env.NODE_VERSION || 'not-set' }}"
          echo "PROD_SUPABASE_URL: $(echo '${{ secrets.PROD_SUPABASE_URL || secrets.VITE_SUPABASE_URL || 'https://demo.supabase.co' }}' | head -c 20)***"
          echo "SENTRY_DSN: $(echo '${{ secrets.VITE_SENTRY_DSN || 'not-set' }}' | head -c 20)***"
          echo "✅ Production environment debug completed"
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION || '18' }}
          cache: 'npm'
          
      - name: Install dependencies
        run: |
          set -e
          echo "📦 Installing dependencies for production..."
          npm ci || {
            echo "❌ Production dependency installation failed"
            exit 1
          }
          echo "✅ Production dependencies installed"
        
      - name: Run production build
        run: |
          set -e
          echo "🏗️ Building for production environment..."
          npm run build || {
            echo "❌ Production build failed"
            exit 1
          }
          echo "✅ Production build completed"
        env:
          VITE_SUPABASE_URL: ${{ secrets.PROD_SUPABASE_URL || secrets.VITE_SUPABASE_URL || 'https://demo.supabase.co' }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.PROD_SUPABASE_ANON_KEY || secrets.VITE_SUPABASE_ANON_KEY || 'demo-key' }}
          VITE_SENTRY_DSN: ${{ secrets.VITE_SENTRY_DSN || '' }}
          
      - name: Deploy to production
        run: |
          set -e
          echo "🚀 Deploying to production environment..."
          # Add actual deployment steps here
          echo "✅ Production deployment completed"
        
      - name: Notify deployment
        if: success()
        run: |
          set -e
          echo "📢 Production deployment successful!"
          echo "🎉 Application is now live in production"

  final-status-report:
    name: Final CI Status Report
    runs-on: ubuntu-latest
    needs: [test, security-scan]
    if: always()
    
    steps:
      - name: Generate Final Report
        run: |
          set -e
          echo "# 🎯 CI Pipeline Final Report" 
          echo "================================"
          echo ""
          echo "**Workflow:** ${{ github.workflow }}"
          echo "**Branch:** ${{ github.ref_name }}"
          echo "**Commit:** ${{ github.sha }}"
          echo "**Triggered by:** ${{ github.event_name }}"
          echo ""
          echo "## 📊 Job Results"
          echo ""
          
          TEST_STATUS="${{ needs.test.outputs.test-status || 'unknown' }}"
          SECURITY_STATUS="${{ needs.security-scan.outputs.security-status || 'unknown' }}"
          
          echo "| Job | Status | Outcome |"
          echo "|-----|--------|---------|"
          echo "| Tests | $TEST_STATUS | ${{ needs.test.result }} |"
          echo "| Security | $SECURITY_STATUS | ${{ needs.security-scan.result }} |"
          echo ""
          
          # Overall assessment
          if [[ "$TEST_STATUS" == "success" && "$SECURITY_STATUS" == "success" ]]; then
            echo "## ✅ Overall Status: SUCCESS"
            echo "All critical checks passed! The code is ready for deployment."
          elif [[ "$TEST_STATUS" == "success" ]]; then
            echo "## ⚠️ Overall Status: PARTIAL SUCCESS" 
            echo "Tests passed but security issues need attention."
          else
            echo "## ❌ Overall Status: FAILURE"
            echo "Critical issues found that must be resolved."
          fi
          echo ""
          echo "---"
          echo "*Report generated at $(date -u '+%Y-%m-%d %H:%M:%S UTC')*"